version: "2"

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - /Users/davidh/work/YellowRodPigeon/public_html:/usr/share/nginx/html
      - ./site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - code-network

  php:
    image: php:7-fpm
    volumes:
      - /Users/davidh/work/YellowRodPigeon/public_html:/usr/share/nginx/html
    networks:
      - code-network

networks:
  code-network:
    driver: bridge

